spring:
    profiles:
        active: local

    datasource:
        url: jdbc:mysql://127.0.0.1:3307/patient_pig
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: pig
        password: pig

    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: true

pig:
    LEVEL_1: 1000
    LEVEL_2: 2000
    LEVEL_3: 3000
debug: true
